# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/')),
                ('name', models.CharField(max_length=30)),
                ('descripton', models.TextField()),
                ('time_uloaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ManyToManyField(to='gallery.categories')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(to='gallery.tags'),
        ),
    ]
